import type { AnalysisResult, Finding, Severity } from "./types";

const SEVERITY_HEADINGS: Record<Severity, string> = {
  fail: "Failures",
  warn: "Warnings",
  info: "Info",
};

function formatFindingLine(finding: Finding): string {
  const resources =
    finding.resources.length > 0
      ? finding.resources.map((r) => `\`${r}\``).join(", ")
      : "stack";
  return `- [${finding.ruleId}] ${resources} — ${finding.summary}`;
}

export function toMarkdown(result: AnalysisResult): string {
  const lines: string[] = [
    `# QueueDoctor report — score ${result.score} (${result.band})`,
    "",
    `Format detected: \`${result.format}\``,
    "",
  ];

  if (result.findings.length === 0) {
    lines.push(
      "No issues found for rules we support — still review IAM and business logic.",
      "",
    );
    return lines.join("\n");
  }

  for (const severity of ["fail", "warn", "info"] as Severity[]) {
    const group = result.findings.filter((f) => f.severity === severity);
    if (group.length === 0) continue;
    lines.push(`## ${SEVERITY_HEADINGS[severity]}`, "");
    for (const finding of group) {
      lines.push(formatFindingLine(finding));
    }
    lines.push("");
  }

  lines.push("---", "", "_Generated by QueueDoctor — analysis ran in your browser._", "");
  return lines.join("\n");
}
